export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// export const LOGIN_FACEBOOK_REQUESTING = 'LOGIN_FACEBOOK_REQUESTING';
// export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
// export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR';

// export const LOGIN_MOBILE_REQUESTING = 'LOGIN_MOBILE_REQUESTING';
// export const LOGIN_MOBILE_SUCCESS = 'LOGIN_MOBILE_SUCCESS';
// export const LOGIN_MOBILE_ERROR = 'LOGIN_MOBILE_ERROR';

export const LOGIN_SHOW_HIDDEN_MODAL = 'LOGIN_SHOW_HIDDEN_MODAL';

export const LOGIN_CHANGE_FORM = 'LOGIN_CHANGE_FORM';
export const LOGIN_RESET_STATES = 'LOGIN_RESET_STATES';